name: Update Weather

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch: # Manual trigger

jobs:
  update-weather:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Specify the Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Fetch Weather Data
        env:
          OPEN_WEATHER: ${{ secrets.OPEN_WEATHER }} # Use the secret as an environment variable
        run: |
          echo "Fetching Weather Data..."
          node fetchWeather.js

      - name: Commit and push if changed
        run: |
          echo "Configuring Git..."
          git config --global user.email "hyates1@gmail.com"
          git config --global user.name "Harry-Yates"
          echo "Fetching latest from main branch..."
          git fetch origin main
          echo "Resetting to the latest commit..."
          git reset --hard FETCH_HEAD
          echo "Checking for changes in README.md..."
          git add README.md
          git status
          git diff-index --quiet HEAD || (echo "Changes detected, committing..." && git commit -m "Update Weather" && git push origin main || echo "No changes to commit")
