name: Update Weather

on:
  schedule:
    - cron: "*/2 * * * *" # Runs every 30 minutes
  workflow_dispatch: # Manual trigger

jobs:
  update-weather:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
        name: Checkout Repository

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "v21.1.0" # Specify the Node.js version

      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          npm install
          echo "Dependencies installed."

      - name: Fetch Weather Data
        working-directory: ./ # Set the working directory to the root of the repository
        env:
          OPEN_WEATHER: ${{ secrets.OPEN_WEATHER }} # Use the secret as an environment variable
        run: |
          echo "Fetching Weather Data..."
          node fetchWeather.js
          echo "Weather Data Fetched."

      - name: Debugging Information Before Git Operations
        run: |
          echo "Current Directory:"
          pwd
          echo "List Files:"
          ls -la
          echo "Git Status Before Changes:"
          git status

      - name: Commit and push if changed
        run: |
          echo "Configuring Git..."
          # git config --global user.email "hyates1@gmail.com"
          # git config --global user.name "Harry-Yates"
            git config --global user.name "Aeolus"
            git config --global user.email "Aeolus@Aeolus.com"
          echo "Git Configuration Set."

          echo "Fetching latest from main branch..."
          git fetch origin main || (echo "Failed to fetch from main" && exit 1)
          echo "Latest fetched."

          echo "Checking for changes in README.md..."
          git add README.md || (echo "Failed to add README.md" && exit 1)
          echo "README.md added."

          echo "Git Status After Changes:"
          git status

          echo "Git Diff:"
          git diff

          git diff-index --quiet HEAD || (echo "Changes detected, committing..." && git commit -m "Shifts the Weather" || (echo "Failed to commit changes" && exit 1))
          echo "Changes Committed."

          echo "Pushing changes to main branch..."
          git push origin main || (echo "Push failed" && exit 1)
          echo "Push successful."

      - name: Debugging Information After Git Operations
        run: |
          echo "Git Status After Push:"
          git status
          echo "Git Log:"
          git log -n 5
