name: Update Weather

on:
  schedule:
    - cron: "*/30 * * * *" # Runs every 30 minutes
  workflow_dispatch: # Manual trigger

jobs:
  update-weather:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Specify the Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Fetch Weather Data
        working-directory: ./ # Set the working directory to the root of the repository
        env:
          OPEN_WEATHER: ${{ secrets.OPEN_WEATHER }} # Use the secret as an environment variable
        run: |
          echo "Fetching Weather Data..."
          node fetchWeather.js

      - name: Commit and push if changed
        run: |
          echo "Configuring Git..."
          git config --global user.email "hyates1@gmail.com"
          git config --global user.name "Harry-Yates"
          echo "Fetching latest from main branch..."
          git fetch origin main || (echo "Failed to fetch from main" && exit 1)
          echo "Resetting to the latest commit..."
          git reset --hard FETCH_HEAD || (echo "Failed to reset to FETCH_HEAD" && exit 1)
          echo "Checking for changes in README.md..."
          git add README.md || (echo "Failed to add README.md" && exit 1)
          git status
          git diff-index --quiet HEAD || (echo "Changes detected, committing..." && git commit -m "Update Weather" || (echo "Failed to commit changes" and exit 1))
          echo "Pushing changes to main branch..."
          git push origin main || (echo "Push failed" && exit 1)
          echo "Push successful"
